---
apiVersion: v1
kind: Secret
metadata:
  name: ainekeenan-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-ms/ainekeenan-gateway-gitops
